BicycleShopSol/BicycleShop/Controllers/VerificationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.Extensions.Configuration;
using BicycleShop.Services;

namespace BicycleShop.Controllers
{
    public class VerificationController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly Email _email;

        public VerificationController(IConfiguration configuration, Email email)
        {
            _configuration = configuration;
            _email = email;
        }

        public IActionResult SendEmail(string userEmail)
        {
            var rand = new Random();

            string code = Math.Round(rand.NextDouble() * rand.Next(1, 10), 4)
                                                                        .ToString()
                                                                                .Replace(",", "");

            _email.SendEmailCode(userEmail, code, "E-mail verification");

            return RedirectToAction("VerificateEmail", new { code = code });
        }

        public IActionResult VerificateEmail(string code)
        {
            ViewBag.Code = code;

            return View();
        }

        [HttpPost]
        public IActionResult VerificateEmail(string code, string confirmation)
        {
            if (confirmation == code)
            {
                return RedirectToAction("AddUserToDB", "Account");
            }

            TempData["verific-state"] = "Verification failed!";

            return RedirectToAction("Signup", "Account");
        }
    }
}

BicycleShopSol/BicycleShop/Views/Verification/VerificateEmail.cshtml
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body class="bg-dark">
        <div class="d-flex justify-content-center pt-3 pb-3 rounded shadow-lg">
            <div class="d-flex justify-content-center col-6">
                <img class="mb-4 w-100" src="https://images.vexels.com/media/users/3/136865/isolated/preview/7221ccf73801a7e9729d11d505fcff2b-smartphone-on-hand.png" alt="">
            </div>
            <div class="d-flex justify-content-center mt-5 mr-5">
                @using (Html.BeginForm("VerificateEmail", "Verification", FormMethod.Post, new { @class = "w-100" }))
                {
                    <h1 class="h3 mb-3 text-white">Enter code, you received by e-mail</h1>
                    <input type="text" class="form-control mb-5" id="code" name="confirmation" placeholder="12345">

                    <input type="hidden" name="code" value=@ViewBag.Code />

                    <button class="w-50 btn btn-info border border-white" type="submit">Confirm</button>
                }
            </div>
        </div>
    </body>
</html>